export const FETCH_SETTINGS_PENDING = 'FETCH_SETTINGS_PENDING';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR';
export const SAVE_SETTINGS_PENDING = 'SAVE_SETTINGS_PENDING';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const FETCH_BUILDS_PENDING = 'FETCH_BUILDS_PENDING';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';
export const FETCH_BUILDS_ERROR = 'FETCH_BUILDS_ERROR';
export const BUILDS_UPDATE_OFFSET = 'BUILDS_UPDATE_OFFSET';
export const BUILDS_CLEAR_STATE = 'BUILDS_CLEAR_STATE';

export const FETCH_BUILD_PENDING = 'FETCH_BUILD_PENDING';
export const FETCH_BUILD_SUCCESS = 'FETCH_BUILD_SUCCESS';
export const FETCH_BUILD_ERROR = 'FETCH_BUILD_ERROR';
export const FETCH_BUILD_LOG_SUCCESS = 'FETCH_BUILD_LOG_SUCCESS';
export const FETCH_BUILD_LOG_ERROR = 'FETCH_BUILD_LOG_ERROR';
export const ADD_BUILD_PENDING = 'ADD_BUILD_PENDING';
export const ADD_BUILD_SUCCESS = 'ADD_BUILD_SUCCESS';
export const ADD_BUILD_ERROR = 'ADD_BUILD_ERROR';
export const ADD_BUILD_TO_VIEW = 'ADD_BUILD_TO_VIEW';
export const CLEAR_BUILD_TO_VIEW = 'CLEAR_BUILD_TO_VIEW';